import { Josefin_Sans } from "next/font/google";
import { Roboto } from "next/font/google";

import localFont from 'next/font/local'

import "./globals.css";

const josefin = Josefin_Sans({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"], variable: '--font-roboto' });

const monea = localFont({
  src: [
    {
      path: '../../public/fonts/MoneaAlegante.otf'
    },
  ],
  variable: '--font-monea'
});

export const metadata = {
  title: "Yssa Creatives",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body className={`${josefin.className} ${roboto.variable} ${monea.variable} relative`}>{children}</body>
    </html>
  );
}
